name: Trigger Submodule Update

on:  
  push:
    paths-ignore:
      - 'data/locales/translations/src/*.json'
      - '.github/**/*.*'
      - '.gitignore'
      - '.vscode/**/*.*'
      - 'README.md'

jobs:
  runCURL:
    runs-on: ubuntu-latest
   
    steps:
      - run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -u ${{ secrets.API_TOKEN }} \
            https://api.github.com/repos/alextim/s-bars/actions/workflows/submodule-update.yml/dispatches \
            -d '{"ref": "'"${GITHUB_REF}"'"}'
